In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score
from tkinter import*
from tkinter import messagebox

C:\Users\Dell\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
# Read the dataset and preprocess it
df = pd.read_csv('Placement_Data_Full_Class.csv')
df['salary'] = df['salary'].fillna(df['salary'].mean())
df['status']= df['status'].map({'Placed':1,'Not Placed':0})
df['workex']= df['workex'].map({'Yes':1,'No':0})
df['gender']= df['gender'].map({'M':1,'F':0})
df['degree_t']= df['degree_t'].map({'Sci&Tech':0,'Comm&Mgmt':1,'Others':2})
df['specialisation']= df['specialisation'].map({'Mkt&HR':1,'Mkt&Fin':0})

In [3]:
df.drop(['sl_no','ssc_p','ssc_b','hsc_b','hsc_s','etest_p','mba_p','salary'],axis = 1,inplace = True)

In [4]:
df.head(10)

   gender  hsc_p  degree_p  degree_t  workex  specialisation  status
0       1  91.00     58.00         0       0               1       1
1       1  78.33     77.48         0       1               0       1
2       1  68.00     64.00         1       0               0       1
3       1  52.00     52.00         0       0               1       0
4       1  73.60     73.30         1       0               0       1
5       1  49.80     67.25         0       1               0       0
6       0  49.20     79.00         1       0               0       0
7       1  64.00     66.00         0       1               0       1
8       1  79.00     72.00         1       0               0       1
9       1  70.00     61.00         1       0               0       0

In [5]:
# Split the dataset into training and test sets
X = df[['hsc_p','degree_p','workex','gender','degree_t','specialisation']]
y = df['status']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a KNN model
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
prediction = knn.predict(X_test)

In [6]:
#x data for a placed predection

x = np.array([[64.00,66.00 , 1, 1 ,0,1]])
y_pred = knn.predict(x)
prediction = 'Hired' if y_pred[0] == 1 else 'Not Hired'
print(prediction)

Hired

In [7]:
x = np.array([[64.00,50.00 , 1, 1 ,0,1]])
y_pred = knn.predict(x)
prediction = 'Hired' if y_pred[0] == 1 else 'Not Hired'
print(prediction)

Not Hired

In [8]:
#predict button
def KNN_predict():
    # Get the user-provided feature values
    hsc_p = hsc_p_entry.get()
    degree_p = degree_p_entry.get()
    workex = workex_entry.get()
    gender = gender_entry.get()
    degree_t = degree_t_entry.get()
    specialisation = specialisation_entry.get()
    

    # Convert the feature values to a numpy array
    x = np.array([[hsc_p, degree_p, workex, gender, degree_t, specialisation]])

    # Make a prediction using the trained KNN model
    y_pred = knn.predict(x)

    # Map the prediction back to the original label
    prediction = 'Hired' if y_pred[0] == 1 else 'Not Hired'
    prediction_label.configure(text=prediction) 
    
    # Display a pop-up message with the prediction
    messagebox.showinfo("Prediction", prediction)

In [9]:
def clear_fields():
    # Clear the text of the input fields
    hsc_p_entry.delete(0, 'end')
    degree_p_entry.delete(0, 'end')
    workex_entry.delete(0, 'end')
    gender_entry.delete(0, 'end')
    degree_t_entry.delete(0, 'end')
    specialisation_entry.delete(0, 'end')
    prediction_label.config(text="")
    
def close_window():
    # Close the window
    root.destroy()

In [13]:
# Create a GUI to get user input and display the prediction
root = Tk()
root.title("Placement Prediction")
root.geometry("500x550")
root.configure(bg="light green")


#create a title
title_label = Label(root,text="GUI For Predecting students hired or not",font = ('Helvetica',15,'bold'),
                    bg="light green",relief="solid").pack()



# Create input fields for the features

hsc_p_label = Label(root, text="High Sec School Degree:",font = ('Helvetica',15,'bold'),
                    bg="light green",relief="solid").place(x=20,y=100,height=30,width=300)
hsc_p_entry = Entry(root)
hsc_p_entry.place(x=340,y=106,height=20)

degree_p_label = Label(root, text="College Degree:",font = ('Helvetica',15,'bold'),
                    bg="light green",relief="solid").place(x=20,y=150,height=30,width=300)
degree_p_entry = Entry(root)
degree_p_entry.place(x=340,y=156,height=20)

workex_label = Label(root, text="Experience(Y:1 , N:0):",font = ('Helvetica',15,'bold'),
                    bg="light green",relief="solid").place(x=20,y=200,height=30,width=300)
workex_entry = Entry(root)
workex_entry.place(x=340,y=206,height=20)


gender_label = Label(root, text="Gender(M:1 , F:0):",font = ('Helvetica',15,'bold'),
                    bg="light green",relief="solid").place(x=20,y=250,height=30,width=300)
gender_entry = Entry(root)
gender_entry.place(x=340,y=256,height=20)

degree_label = Label(root, text="Degree Type(COMM:0 , SCI:1):",font = ('Helvetica',15,'bold'),
                    bg="light green",relief="solid").place(x=20,y=300,height=30,width=300)
degree_t_entry = Entry(root)
degree_t_entry.place(x=340,y=306,height=20)

specialisation_label = Label(root, text="Specialization(FIN:0 , HR:1):",font = ('Helvetica',15,'bold'),
                    bg="light green",relief="solid").place(x=20,y=350,height=30,width=300)
specialisation_entry = Entry(root)
specialisation_entry.place(x=340,y=356,height=20)


#predict button
predict_button = Button(root, text="Predict", command=KNN_predict,height=1,width=10).place(x=90,y=420)

#clear button
clear_button = Button(root, text="Clear",command=clear_fields,height=1,width=10).place(x=190,y=420)

#exit button
exit_button = Button(root, text="Exit",command=close_window,height=1,width=10).place(x=290,y=420)

# Create a label to display the prediction
prediction_label = Label(root)
prediction_label.place(x=142,y=480,height=25,width=178)


root.resizable(0,0)
root.mainloop()